// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/writer-ron-home/Atelier.tsx": () => import("../components/mockups/writer-ron-home/Atelier.tsx"),
  "./components/mockups/writer-ron-home/BrightStudio.tsx": () => import("../components/mockups/writer-ron-home/BrightStudio.tsx"),
  "./components/mockups/writer-ron-home/Command.tsx": () => import("../components/mockups/writer-ron-home/Command.tsx")
};
